name: Build-Front
on:
  push:
    branches:
      - main #빌드하고싶은 브랜치
    # paths:
    #   - front/**
jobs:
  build-front:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') && github.path == 'front/**'
    runs-on: ubuntu-latest
    # paths:
    #   - front/**
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm Install
        working-directory: front
        run: |
          npm install
      - name: Npm Build
        working-directory: front
        run: |
          npm run build
      - name: Upload /build to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: "front/dist"
  build-back:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') && startsWith(github.path, 'back/')
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Create application.properties
        run: |
          echo "${{ secrets.APPLICATION }}" > ./back/src/main/resources/application.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./back/gradlew

      - name: Build without Test in Gradle
        run: ./gradlew build -x test
        working-directory: ./back
