name: Build-Front
on:
  push:
    branches:
      - main #빌드하고싶은 브랜치
    paths:
      - front/**
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Create env file
      #   run: |
      #     touch .env
      #     echo AWS_STAGING_BUCKET_NAME=${{ secrets.AWS_STAGING_BUCKET_NAME }} >> .env
      #     echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
      #     echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
      #     echo AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} >> .env
      #     # ...이런식으로 환경 변수 삽입
      #     cat .env
      - name: Npm Install
        working-directory: front
        run: |
          npm install
      - name: Npm Build
        working-directory: front
        run: |
          npm run build
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-2
      - name: Upload /build to S3
        working-directory: front
        #   env:
        #     BUCKET_NAME: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
        #   run: |
        #     aws s3 cp --recursive --region ap-northeast-2 dist s3://$BUCKET_NAME
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: "dist"
# name: Build-Back
# on:
#   pull_request:
#     paths:
#       - "back/**"
#     branches: [main, develop]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'corretto'

#       - name: Create application.properties
#         run: |
#           echo "${{ secrets.APPLICATION }}" > ./back/src/main/resources/application.properties

#       - name: Grant execute permission for gradlew
#         run: chmod +x ./back/gradlew

#       - name: Build without Test in Gradle
#         run: ./gradlew build -x test
#         working-directory: ./back
